/** All user-visible text lives here (localization stays possible). */
export const S = {
  appName: "Omni",
  tagline: "Your machines, your agents.",
  hosts: "Hosts",
  workspaces: "Workspaces",
  tasks: "Tasks",
  login: "Log in",
  logout: "Log out",
  setupTitle: "Create the admin account",
  setupHint: "First run — this can be done exactly once.",
  setupCta: "Create account",
  setupDone: "The admin account already exists — log in instead.",
  loginTitle: "Log in to Omni",
  username: "Username",
  password: "Password",
  firstTime: "First time here? Create the admin account",
  haveAccount: "Already set up? Log in",
  addHost: "Add host",
  addHostTitle: "Add a host",
  hostName: "Host name",
  hostNamePlaceholder: "e.g. macmini",
  createHost: "Create host",
  enrollInstructions:
    "Run this command on the machine you are enrolling. The token is one-time and expires in 15 minutes — it is shown only once.",
  copyCommand: "Copy command",
  copied: "Copied",
  done: "Done",
  online: "online",
  offline: "offline",
  pending: "awaiting enrollment",
  lastSeen: (ago: string) => `last seen ${ago}`,
  neverSeen: "never connected",
  harnesses: "Harnesses",
  noHarnesses: "No harnesses detected yet",
  rename: "Rename",
  renameTitle: "Rename host",
  save: "Save",
  cancel: "Cancel",
  rotate: "Rotate credential",
  rotateTitle: "Rotate credential",
  rotateWarning:
    "Rotating disconnects the host and requires re-enrollment with a new token. Continue?",
  rotateCta: "Rotate & disconnect",
  deleteHost: "Delete",
  deleteTitle: "Delete host",
  deleteWarning: (name: string) =>
    `Delete “${name}”? Its credential and queued commands are removed. This cannot be undone.`,
  deleteCta: "Delete host",
  noHosts: "No hosts yet — add one to get started.",
  errorGeneric: "Something went wrong",
  justNow: "just now",
  minutesAgo: (n: number) => (n === 1 ? "1 minute ago" : `${n} minutes ago`),
  hoursAgo: (n: number) => (n === 1 ? "1 hour ago" : `${n} hours ago`),
  loading: "Loading…",
} as const;
